feat: update broadcast workflow and configuration files for improved file replication

diff --git a/.github/workflows/broadcast-files.yaml b/.github/workflows/broadcast-files.yaml
--- a/.github/workflows/broadcast-files.yaml
+++ b/.github/workflows/broadcast-files.yaml
@@ -1,5 +1,6 @@
 ---
 name: Broadcast files to organization
+run-name: "${{ inputs.config-file }}. ${{ inputs.section }} files broadcast to ${{ inputs.repos || 'all repositories' }}"
 on:
   workflow_dispatch:
     inputs:
@@ -9,44 +10,81 @@ on:
           If not provided, the action will be triggered for all repositories in the organization.
         required: false
         type: string
-      replicate-common-files:
-        description: 'Replicate common files'
-        required: false
-        default: false
-        type: boolean
+      config-file:
+        description: 'Config file relative path'
+        required: true
+        type: string
+        default: '.github/broadcast-files-config.yaml'
+      section:
+        description: 'Name of the dict in config file'
+        required: true
+        type: string
 
 permissions:
   contents: read
   pull-requests: write
   statuses: read
 jobs:
-  setup_matrix:
+  setup_jobs:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.setup_matrix.outputs.matrix }}
+      config: ${{ steps.setup_matrix.outputs.config }}
     steps:
+      - uses: actions/checkout@v4
       - id: setup_matrix
         run: |
           if [[ "${{ inputs.repos }}" != "" ]]; then
             CSV_STRING="${{ inputs.repos }}"
             JSON_MATRIX=$(jq -c -n --arg in_str "$CSV_STRING" '$in_str | split(",")')
-            echo "matrix={\"item\":$JSON_MATRIX}"
-            echo "matrix={\"item\":$JSON_MATRIX}" >> $GITHUB_OUTPUT
+            echo "matrix=$JSON_MATRIX"
+            echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT
           else
-            echo "matrix={\"item\":[\"\"]}"
-            echo "matrix={\"item\":[\"\"]}" >> $GITHUB_OUTPUT
+            echo "matrix=[\"\"]"
+            echo "matrix=[\"\"]" >> $GITHUB_OUTPUT
+          fi
+          if [[ -f "${{ inputs.config-file }}" ]]; then
+            wget -q https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O yq
+            chmod +x yq
+            sudo mv yq /usr/local/bin/yq
+            if [[ "${{ inputs.section }}" != "" ]]; then
+              settings=$(yq eval ".${{ inputs.section }}" "${{ inputs.config-file }}" -o=json | jq -c '{settings: .}')
+            else
+              echo "::error::Config file section not specified!"
+              echo "[ERROR]: Config file section not specified!" >> $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
+            echo "config=$settings" >> $GITHUB_OUTPUT
+          else
+            echo "::error::Config file '${{ inputs.config-file }}' not found."
+            echo "[ERROR]: Config file '${{ inputs.config-file }}' not found." >> $GITHUB_STEP_SUMMARY
+            exit 1
           fi
 
-  replicate_common_files:
-    needs: setup_matrix
-    name: Replicating common git files
+  replicate_files:
+    needs: setup_jobs
+    name: Replicating files
     strategy:
       fail-fast: false
-      matrix: ${{ fromJson(needs.setup_matrix.outputs.matrix) }}
-    if: ${{ inputs.replicate-common-files }}
-    uses: myborislavrorg/broadcast/.github/workflows/reusable-broadcast-files.yaml@main
-    with:
-      replicate-common-files: ${{ inputs.replicate-common-files }}
-      repo_name: "${{ matrix.item }}"
-    secrets:
-      token: '${{ secrets.BORISLAVR_PAT }}'
+      matrix:
+        repo: ${{ fromJson(needs.setup_jobs.outputs.matrix) }}
+        config: ${{ fromJson(needs.setup_jobs.outputs.config) }}
+      max-parallel: 10
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Replicating files
+        uses: borislavr/manage-files-in-multiple-repositories@main
+        with:
+          github_token: '${{ secrets.BORISLAVR_PAT }}'
+          exclude_private: true
+          exclude_forked: false
+          committer_username: borislavr
+          bot_branch_name: ${{ matrix.config.settings.bot_branch_name || 'broadcast-files' }}
+          patterns_to_include: ${{ matrix.config.settings.patterns_to_include || '' }}
+          destination: ${{ matrix.config.settings.destination || '.' }}
+          commit_message: ${{ matrix.config.settings.commit_message || 'chore: update of common files' }}
+          repo_name: ${{ matrix.repo }}
+          patterns_to_ignore: ${{ matrix.config.settings.patterns_to_ignore || '' }}
+          patterns_to_remove: ${{ matrix.config.settings.patterns_to_remove || '' }}
